2016_RERECO:  # recommendation from https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVAnalysisSummaryTable
  data_B: /SingleMuon/Run2016B-02Apr2020_ver2-v1/NANOAOD
  data_C: /SingleMuon/Run2016C-02Apr2020-v1/NANOAOD
  data_D: /SingleMuon/Run2016D-02Apr2020-v1/NANOAOD
  data_E: /SingleMuon/Run2016E-02Apr2020-v1/NANOAOD
  data_F: /SingleMuon/Run2016F-02Apr2020-v1/NANOAOD
  data_G: /SingleMuon/Run2016G-02Apr2020-v1/NANOAOD
  data_H: /SingleMuon/Run2016H-02Apr2020-v1/NANOAOD
